{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notifications
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.metrics.prometheusReleaseLabel | default "kube-prometheus-stack" }}
spec:
  selector:
    matchLabels:
      app: notifications
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
