apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tickets.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: tickets
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: SERVICE_VERSION
              value: "{{ .Values.serviceVersion | default "1.0.0" }}"
            - name: GIT_SHA
              value: "{{ .Values.gitSha | default "unknown" }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
